### ISSUE TITLE
Surprising `list*` behavior

### ISSUE THREAD

**Issue by sjl** [guicho271828/trivia#64]
I was trying to match the contents of a list to do something with it, like this:

```lisp
(match foo
  ; if foo is a list, transform its contents
  ((list* contents) (mapcar #'whatever contents))
  ; otherwise...
)
```

But it appears that `list*` with a single argument will just match anything at all:

```lisp
(match 'x ((list* foo) foo))
X
```

The docs in the wiki for `list` and `list*` say:

> Both patterns checks if the object is of type list

so this seems like a bug in either the matcher or the docs...

**Comment by guicho271828** [comment]
Well, this is a tricky thing and I discussed it with somebody else once.
The doc should be fixed. The reasoning behind this decision is as follows:

Since pattern matching & destructuring is a dual operation of object creation, it is better if the behavior reflects the original function. And the `list*` on clhs says: 

http://clhs.lisp.se/Body/f_list_.htm

    If list* receives only one object, that object is returned, regardless of whether or not it is a list. 

I will fix both the wiki documentation and docstring.
